# Generated by Django 5.0.1 on 2025-06-04 18:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('numCategorie', models.AutoField(primary_key=True, serialize=False)),
                ('nomCategorie', models.CharField(max_length=50)),
                ('imageCategorie', models.ImageField(null=True, upload_to='images/produits/categories/')),
                ('descCategorie', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('numClassement', models.AutoField(primary_key=True, serialize=False)),
                ('nomClassement', models.CharField(max_length=20)),
                ('quantiteMin', models.FloatField()),
                ('quantiteMax', models.FloatField(null=True)),
                ('descClassement', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Classement',
                'verbose_name_plural': 'Classements',
                'db_table': 'classement',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('numClient', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=17, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('contact', models.CharField(max_length=17)),
                ('image', models.ImageField(null=True, upload_to='images/utilisateurs/')),
                ('adresse', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('numCommande', models.AutoField(primary_key=True, serialize=False)),
                ('dateCommande', models.DateTimeField()),
                ('reference', models.CharField(max_length=30, null=True)),
                ('numClient', models.ForeignKey(db_column='numClient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='flutter.client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'commande',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('numProduit', models.AutoField(primary_key=True, serialize=False)),
                ('libelleProduit', models.CharField(max_length=20)),
                ('quantite', models.FloatField(default=0)),
                ('uniteMesure', models.CharField(null=True, verbose_name=10)),
                ('description', models.TextField(null=True)),
                ('numCategorie', models.ForeignKey(db_column='numCategorie', on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='flutter.categorie')),
                ('numClassement', models.ForeignKey(db_column='numClassement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='flutter.classement')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'produit',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('numImage', models.AutoField(primary_key=True, serialize=False)),
                ('nomImage', models.ImageField(null=True, upload_to='images/produits/')),
                ('numProduit', models.ForeignKey(db_column='numProduit', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flutter.produit')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Comprendre',
            fields=[
                ('numComprendre', models.AutoField(primary_key=True, serialize=False)),
                ('quantiteCommande', models.FloatField(default=0)),
                ('numCommande', models.ForeignKey(db_column='numCommande', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprendres', to='flutter.commande')),
                ('numProduit', models.ForeignKey(db_column='numProduit', on_delete=django.db.models.deletion.CASCADE, related_name='comprendres', to='flutter.produit')),
            ],
            options={
                'verbose_name': 'Comprendre',
                'verbose_name_plural': 'Comprendres',
                'db_table': 'comprendre',
            },
        ),
    ]
