# Generated by Django 5.0.1 on 2025-06-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0002_produit_prixunitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='qrCode',
            field=models.ImageField(blank=True, null=True, upload_to='images/produits/qrcode/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='nomImage',
            field=models.ImageField(null=True, upload_to='images/produits/images/'),
        ),
    ]
