# Generated by Django 5.0.1 on 2025-06-09 19:03

import flutter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0003_produit_qrcode_alter_image_nomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='imageCategorie',
            field=models.ImageField(null=True, upload_to='images/produits/categories/'),
        ),
    ]
