# Generated by Django 5.0.1 on 2025-06-21 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0004_alter_categorie_imagecategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='dateCommande',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
