# Generated by Django 5.0.1 on 2025-06-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0005_alter_commande_datecommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='reference',
            field=models.CharField(default='Commande-<django.db.models.fields.AutoField>', max_length=30, null=True),
        ),
    ]
