# Generated by Django 5.0.1 on 2025-06-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0006_alter_commande_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='reference',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
