# Generated by Django 5.0.1 on 2025-06-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0007_alter_commande_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='contact',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
