# Generated by Django 5.0.1 on 2025-07-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0009_alter_produit_numcategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
